# Generated by Django 5.0.3 on 2024-08-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('branch', models.CharField(choices=[('ME', 'ME'), ('CSE', 'CSE'), ('ECE', 'ECE'), ('AI', 'AI'), ('ML', 'ML')], max_length=20)),
            ],
        ),
    ]
